name: Maven Reusable Workflow
run-name: GitHub Action Maven Reusable Workflow
on:
  workflow_dispatch:
  workflow_call:
jobs:
  Test-Workflow:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout tools repo
      uses: actions/checkout@v4
      with:
        repository: anujdevopslearn/PythonTest
        path: test
        ref: 'master'
        token: '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'
    - name: Invoke Python script
      run: python -m unittest discover
      working-directory: test/example-py-unittest/
